#!/usr/bin/env bash
# https://developer.1password.com/docs/cli/get-started/

set -e

OS=$(uname -a | tr '[:lower:]' '[:upper:]')
MAC='DARWIN'
LINUX='LINUX'
WSL='MICROSOFT'

SIGNIN=$(op signin --account my.1password.com)
eval "$SIGNIN"

ENTRY=$(op item list --format=json | jq -c '.[] | {title: (.title), id: (.id)}' | fzf)

if [ -n "$ENTRY" ]; then
	ITEM_ID=$(echo "$ENTRY" | jq '.id' | tr -d '"')
    PASS=$(op item get "$ITEM_ID" --fields label=password)

	case $OS in
	*$MAC*)
		echo "$PASS" | pbcopy
		;;
	*$LINUX*)
		if [[ $OS =~ $WSL ]]; then
			echo "$PASS" | win32yank.exe -i
		else
			echo "$PASS" | xclip -selection -c
		fi
		;;
	*)
		>&2 echo "Unable to detect OS to determine clipboard executable"
		exit 1
		;;
	esac

	echo "Copied password to clipboard!"
	echo "$ENTRY" | jq '. | {title: (.title), password: "**********"}'
fi
