#!/usr/bin/env bash

eval $(op signin my)

ENTRY=$(op list items | jq -c '.[] | {title: (.overview.title), url: (.overview.url), uuid: (.uuid)}' | fzf)

if [ ! -z "$ENTRY" ]; then
	ITEM_ID=$(echo $ENTRY | jq '.uuid' | tr -d '"')
	op get item "$ITEM_ID" --fields title,url,username,password | jq '.'
fi
