#!/usr/bin/env bash

set -e

OS=$(uname -a | tr '[:lower:]' '[:upper:]')
MAC='DARWIN'
LINUX='LINUX'
WSL='MICROSOFT'

SIGNIN=$(op signin --account my.1password.com)
eval "$SIGNIN"

ENTRY=$(op item list --format=json | jq -c '.[] | {title: (.title), id: (.id)}' | fzf)

if [ -n "$ENTRY" ]; then
	ITEM_ID=$(echo "$ENTRY" | jq '.id' | tr -d '"')
    ITEM=$(op item get "$ITEM_ID" --format=json)

	case $OS in
	*$MAC*)
		echo "$ITEM" | jq '.password' | tr -d '"' | pbcopy
		;;
	*$LINUX*)
		if [[ $OS =~ $WSL ]]; then
			echo "$ITEM" | jq '.password' | tr -d '"' | win32yank.exe -i
		else
			echo "$ITEM" | jq '.password' | tr -d '"' | xclip -selection -c
		fi
		;;
	*)
		>&2 echo "Unable to detect OS to determine clipboard executable"
		exit 1
		;;
	esac

	echo "Copied password to clipboard!"
	echo "$ITEM" | jq '. | {title: (.title), username: (.username), password: "*****"}'
fi
