#!/usr/bin/env bash

set -e

OS=$(uname -a | tr '[:lower:]' '[:upper:]')
MAC='DARWIN'
LINUX='LINUX'
WSL='MICROSOFT'

SIGNIN=$(op signin --account my.1password.com)
eval "$SIGNIN"

ENTRY=$(op item list --format=json | jq -c '.[] | {title: (.title), id: (.id)}' | fzf)

if [ -n "$ENTRY" ]; then
	ITEM=$(echo "$ENTRY" | jq '.id' | tr -d '"')
	TOKEN=$(op item get --otp "$ITEM")

	case $OS in
	*$MAC*)
		echo "$TOKEN" | pbcopy
		;;
	*$LINUX*)
		if [[ $OS =~ $WSL ]]; then
			echo "$TOKEN" | win32yank.exe -i
		else
			echo "$TOKEN" | xclip -selection -c
		fi
		;;
	*)
		>&2 echo "Unable to detect OS to determine clipboard executable"
		exit 1
		;;
	esac

	echo "Copied token to clipboard!"
	echo "$ENTRY" | jq '. | {title: (.title), token: "****"}'
fi
