#!/usr/bin/env bash

eval $(op signin my)

OS=$(uname -a | tr '[:lower:]' '[:upper:]')
MAC='DARWIN'
LINUX='LINUX'
WSL='MICROSOFT'

ENTRY=$(op list items | jq -c '.[] | {title: (.overview.title), url: (.overview.url), uuid: (.uuid)}' | fzf)

if [ ! -z "$ENTRY" ]; then
	ITEM=$(echo $ENTRY | jq '.uuid' | tr -d '"')
	TOKEN=$(op get totp "$ITEM")

	case $OS in
	*$MAC*)
		echo $TOKEN | pbcopy
		;;
	*$LINUX*)
		if [[ $OS =~ $WSL ]]; then
			echo $TOKEN | win32yank.exe -i
		else
			echo $TOKEN | xclip -selection -c
		fi
		;;
	esac

	echo "Copied token to clipboard!"
	echo $ENTRY | jq '. | {title: (.title), url: (.url), token: "****"}'
fi
