vim.cmd("setlocal expandtab tabstop=4 shiftwidth=4")
-- vim.cmd("setlocal foldlevel=2")
vim.cmd([[ setlocal commentstring=\/\/\ %s ]])
vim.cmd("setlocal filetype=jsonc")
vim.cmd("setlocal conceallevel=0")
