add_newline = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[git_status]
disabled = true

[jobs]
symbol = "+"

[aws]
symbol = "  "

[conda]
symbol = " "

[directory]
read_only = " "
style = "bold cyan"

[docker_context]
symbol = " "

[git_branch]
symbol = " "
style = "bold purple"

[golang]
symbol = " "

[java]
symbol = " "
style = "bold red"

[memory_usage]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

[shlvl]
symbol = " "

[container]
style = "bold purple"

[username]
style_root = "bold red"
style_user = "bold white"

[hostname]
style = "bold yellow"

[localip]
style = "bold green"

[dotnet]
style = "bold blue"

[time]
style = "bold yellow"
