add_newline = false

[git_status]
disabled = false

[jobs]
symbol = "+"

[aws]
symbol = "  "

[conda]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "
style = "bold red"

[memory_usage]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

[shlvl]
symbol = " "

[container]
style = "purple"

[username]
style_root = "red"
style_user = "white"

[hostname]
style = "yellow"

[localip]
style = "green"
