add_newline = false

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[git_status]
disabled = true

[jobs]
symbol = "+"

[aws]
symbol = "  "

[conda]
symbol = " "

[directory]
read_only = " "
style = "cyan"

[docker_context]
symbol = " "

[git_branch]
symbol = " "
style = "purple"

[golang]
symbol = " "

[java]
symbol = " "
style = "bold red"

[memory_usage]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

[shlvl]
symbol = " "

[container]
style = "purple"

[username]
style_root = "red"
style_user = "white"

[hostname]
style = "yellow"

[localip]
style = "green"

[dotnet]
style = "blue"

[time]
style = "yellow"
