autoload -U colors && colors

local OS=$(uname -a)
local MAC='Darwin'
local LINUX='Linux'

case $OS in
*$MAC*)
	alias ls='ls -G'
	alias copy='pbcopy'
	export PATH=/usr/local/sbin:$PATH
	export PATH=/usr/local/bin:$PATH
	export PATH=/usr/local/opt/openssl/bin:$PATH
	export JAVA_HOME=$(/usr/libexec/java_home)
	export GOROOT=/usr/local/opt/go/libexec
	;;
*$LINUX*)
	if (( $+commands[clip.exe] )); then
		alias copy=clip.exe
	else
		alias copy='xclip -selection -c'
	fi
	alias ls='ls --color=auto'
    # When installing from cargo, even on linux, those naming restrictions dont apply
    if (( $+commands[fdfind] )); then
        alias fd='fdfind'
    fi
    if (( $+commands[batcat] )); then
        alias bat='batcat'
    fi
	export GOROOT=/opt/go
	;;
esac

alias luamake=/Users/asidlo/.local/src/lua-language-server/3rd/luamake/luamake

if (( $+commands[tree] )); then
	alias tree='tree -C'
fi

alias ll='ls -AlFG'
alias l='ls'
alias la='ls -AG'
alias grep='grep --color=auto'
alias cls='clear'

if (( $+commands[nvim] )); then
	export VISUAL=nvim
	export EDITOR=nvim
	export MANPAGER="$EDITOR +Man!"
else
	export VISUAL=vim
	export EDITOR=vim
	export MANPAGER="vim -M +MANPAGER -"
fi

export MANWIDTH=999

export GOPATH=$HOME/.local/go
export PATH=$PATH:$GOROOT/bin
export PATH=$PATH:$GOPATH/bin

[[ -v JAVA_HOME ]] && export PATH=$PATH:$JAVA_HOME/bin
[[ -v GRADLE_HOME ]] && export PATH=$PATH:$GRADLE_HOME/bin

LUAROCKS_HOME=~/.local/src/luarocks-3.3.1
[[ -d "$LUAROCKS_HOME/lua_modules/bin" ]] && export PATH=$PATH:"$LUAROCKS_HOME/lua_modules/bin"

[ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"
