autoload -U colors && colors

OS=$(uname -a)
MAC='Darwin'
LINUX='Linux'

case $OS in
*$MAC*)
	alias ls='ls -G'
	alias copy='pbcopy'
	export PATH=/usr/local/opt/openssl/bin:$PATH
	export JAVA_HOME=$(/usr/libexec/java_home)
	# Cocoapods for ios dev
	export PATH=$HOME/.gem/bin:$PATH
	;;
*$LINUX*)
	alias ls='ls --color=auto'
	export GOROOT=/usr/local/go
	if [[ "$OS" =~ "WSL" ]]; then
		MSEDGE_PATH=/mnt/c/Program\ Files\ \(x86\)/Microsoft/Edge/Application/msedge.exe
		if [ -f "$MSEDGE_PATH" ]; then
			if [ ! -L ~/.local/bin/msedge.exe ]; then
				ln -sf "$MSEDGE_PATH" ~/.local/bin/msedge.exe
			fi
			export BROWSER=msedge.exe
		fi
		WIN32YANK_PATH=/mnt/c/tools/neovim/nvim-win64/bin/win32yank.exe
		if [ -f "$WIN32YANK_PATH" ]; then
			if [ ! -L ~/.local/bin/win32yank.exe ]; then
				ln -sf "$WIN32YANK_PATH" ~/.local/bin/win32yank.exe
			fi
		fi
		alias copy="win32yank.exe -i"
	fi
	;;
esac

export PATH=/bin:$PATH
export PATH=/sbin:$PATH
export PATH=/usr/bin:$PATH
export PATH=/usr/sbin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/sbin:$PATH

alias luamake=/Users/asidlo/.local/src/lua-language-server/3rd/luamake/luamake

alias ll='ls -AlFG'
alias l='ls'
alias la='ls -AG'
alias grep='grep --color=auto'
alias cls='clear'

export MANWIDTH=999

export GOPATH=$HOME/.local/go
export PATH=$PATH:$GOROOT/bin
export PATH=$PATH:$GOPATH/bin

[[ -v JAVA_HOME ]] && export PATH=$PATH:$JAVA_HOME/bin
[[ -v GRADLE_HOME ]] && export PATH=$PATH:$GRADLE_HOME/bin

# export DOTNET_ROOT=/usr/local/share/dotnet
export DOTNET_ROOT=~/.dotnet
export PATH=$DOTNET_ROOT:$PATH
export PATH=$DOTNET_ROOT/tools:$PATH

BOB_BIN=~/.local/share/bob/nvim-bin
if [ -d "$BOB_BIN" ]; then
	export PATH=$PATH:$BOB_BIN
fi

# For using gpg for pass and git credential manager
# See https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/credstores.md#gpgpass-compatible-files
export GPG_TTY=$(tty)

LUAROCKS_HOME=~/.local/src/luarocks-3.3.1
if [ -d "$LUAROCKS_HOME/lua_modules/bin" ]; then
	export PATH=$PATH:"$LUAROCKS_HOME/lua_modules/bin"
fi

[ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"

if [ -d "$HOME/.nvm" ]; then
	export NVM_DIR="$HOME/.nvm"
	[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh" || true
	[ -s "$NVM_DIR/bash_completion" ] && source "$NVM_DIR/bash_completion" || true
fi

if [ -d "$HOME/.sdkman" ]; then
	export SDKMAN_DIR="$HOME/.sdkman"
	[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ] && source "$SDKMAN_DIR/bin/sdkman-init.sh" || true
fi
